### ISSUE TITLE
[0.5.0] big icon in "About Eclipse"

### ISSUE THREAD

**Issue by anb0s** [iloveeclipse/javahexeditor#1]
![image](https://cloud.githubusercontent.com/assets/95811/26677273/7d497b5e-46cb-11e7-8c0e-3c2a55ab5d05.png)

**Comment by peterdell** [comment]
Fixed in net.sourceforge.javahexeditor_0.5.1.201708091251.

**Comment by anb0s** [comment]
Verified Java Hex Editor 0.5.1.201708091251 from http://javahexeditor.sourceforge.net/update

Thanks!
